service: serverless-etl-genai

provider:
  name: google
  runtime: nodejs22.x
  region: us-central1
  project: ${env:GCP_PROJECT_ID, 'serverless-etl-genai-project'}
  credentials: ${env:GCP_CREDENTIALS, './service-account-key.json'}
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    OLLAMA_ENDPOINT: ${env:OLLAMA_ENDPOINT, 'http://localhost:11434/api/generate'}
    OLLAMA_MODEL: ${env:OLLAMA_MODEL, 'mistral'}

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
    - tests/**
    - docs/**

functions:
  extract:
    handler: extract
    events:
      - http: extract

  transform:
    handler: transform
    events:
      - http: transform

  load:
    handler: load
    events:
      - http: load

  orchestrator:
    handler: orchestrate
    events:
      - http: orchestrate
      - event:
          eventType: providers/cloud.pubsub/eventTypes/topic.publish
          resource: projects/${self:provider.project}/topics/etl-hourly-trigger 